<a href="https://colab.research.google.com/github/Ziyan-spec/Data-Analysis-/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Basics** **of** **Numpy**





In [62]:
import numpy as np

In [63]:
#1D
a = np.array([1,2,3])
print(type(a))
print(a)

<class 'numpy.ndarray'>
[1 2 3]


In [ ]:
#2D
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
#3D
np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
#data type
np.array([1,2,3],dtype= float)

array([1., 2., 3.])

In [ ]:
#np.arange
b = np.arange(1,10, dtype=np.int32)
print(b.dtype)
print(b)
print(b.ndim)
print(b.shape)

int32
[1 2 3 4 5 6 7 8 9]
1
(9,)


In [ ]:
#reshape
c = np.arange(1,13).reshape(3,4)
print(c.size)
print(c)
print(c.ndim)
print(c.shape)

12
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2
(3, 4)


In [ ]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.random.random((2,3))

array([[0.46078212, 0.41609319, 0.3657688 ],
       [0.7298517 , 0.37175774, 0.49269003]])

In [ ]:
print(a.dtype)
print(b.dtype)

int64
int32


In [ ]:
e = a.astype(np.int32)
print(e.dtype)
print(e)

int32
[1 2 3]


# **Arithmetic** **Operations**

In [ ]:
print(c)
#print(c*2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


# **Relational** **Operators**

In [ ]:
c > 4

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

# **Vector** **Operation**





In [ ]:
d = np.arange(1,13).reshape(3,4)
d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
c + d

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

# **Array** **Functions**

In [60]:
a1 = np.arange(1,13).reshape(3,4)
a1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [68]:
#sum/min/max/product
print(np.sum(a1))
print(f"Max : {np.max(a1)}")
print(np.prod(a1))

78
Max : 12
479001600


In [70]:
print(np.prod(a1,axis=1))

[   24  1680 11880]


In [75]:
#mean/median/std/var
np.var(a1, axis=1)

array([1.25, 1.25, 1.25])