<a href="https://colab.research.google.com/github/Ziyan-spec/Data-Analysis-/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Basics of Numpy

In [3]:
import numpy as np

In [7]:
#1D
a = np.array([1,2,3])
print(type(a))
print(a)

<class 'numpy.ndarray'>
[1 2 3]


In [ ]:
#2D
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
#3D
np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
#data type
np.array([1,2,3],dtype= float)

array([1., 2., 3.])

In [17]:
#np.arange
b = np.arange(1,10, dtype=np.int32)
print(b.dtype)
print(b)
print(b.ndim)

int32
[1 2 3 4 5 6 7 8 9]
1


In [ ]:
#reshape
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.random.random((2,3))

array([[0.46078212, 0.41609319, 0.3657688 ],
       [0.7298517 , 0.37175774, 0.49269003]])

In [8]:
a.dtype

dtype('int64')