<a href="https://colab.research.google.com/github/Ziyan-spec/Data-Analysis-/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Basics of Numpy

In [ ]:
import numpy as np

In [ ]:
#1D
a = np.array([1,2,3])
print(type(a))
print(a)

<class 'numpy.ndarray'>
[1 2 3]


In [ ]:
#2D
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
#3D
np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
#data type
np.array([1,2,3],dtype= float)

array([1., 2., 3.])

In [ ]:
#np.arange
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#reshape
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [3]:
import numpy as np
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])