<a href="https://colab.research.google.com/github/Ziyan-spec/Data-Analysis-/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Basics** **of** **Numpy**





In [1]:
import numpy as np

In [ ]:
#1D
a = np.array([1,2,3])
print(type(a))
print(a)

<class 'numpy.ndarray'>
[1 2 3]


In [ ]:
#2D
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
#3D
np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
#data type
np.array([1,2,3],dtype= float)

array([1., 2., 3.])

In [ ]:
#np.arange
b = np.arange(1,10, dtype=np.int32)
print(b.dtype)
print(b)
print(b.ndim)
print(b.shape)

int32
[1 2 3 4 5 6 7 8 9]
1
(9,)


In [ ]:
#reshape
c = np.arange(1,13).reshape(3,4)
print(c.size)
print(c)
print(c.ndim)
print(c.shape)

12
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2
(3, 4)


In [ ]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.random.random((2,3))

array([[0.46078212, 0.41609319, 0.3657688 ],
       [0.7298517 , 0.37175774, 0.49269003]])

In [ ]:
print(a.dtype)
print(b.dtype)

int64
int32


In [ ]:
e = a.astype(np.int32)
print(e.dtype)
print(e)

int32
[1 2 3]


# **Arithmetic** **Operations**

In [ ]:
print(c)
#print(c*2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


# **Relational** **Operators**

In [ ]:
c > 4

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

# **Vector** **Operation**





In [ ]:
d = np.arange(1,13).reshape(3,4)
d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
c + d

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

# **Array** **Functions**

In [ ]:
a1 = np.arange(1,13).reshape(4,3)
a1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
#sum/min/max/product
print(np.sum(a1))
print(f"Max : {np.max(a1)}")
print(np.prod(a1))

78
Max : 12
479001600


In [ ]:
print(np.prod(a1,axis=1))

[   24  1680 11880]


In [ ]:
#mean/median/std/var
np.var(a1, axis=1)

array([1.25, 1.25, 1.25])

In [ ]:
#trigonometric function
np.sin(a1)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ],
       [ 0.6569866 ,  0.98935825,  0.41211849],
       [-0.54402111, -0.99999021, -0.53657292]])

In [ ]:
#dot product
np.dot(a1,d)

array([[ 38,  44,  50,  56],
       [ 83,  98, 113, 128],
       [128, 152, 176, 200],
       [173, 206, 239, 272]])

In [ ]:
#exponent and log
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [ ]:
#floor/round/ceil
a2 = np.random.random((2,3))*100
print(a2)
print(f"Floor Vector : \n{np.floor(a2)}")
print(f"Round: \n {np.round(a2)}")
print(f"Ceil: \n {np.ceil(a2)}")

[[90.98862778 30.69626863 11.20483423]
 [ 8.27279587  5.43051627 13.61147757]]
Floor Vector : 
[[90. 30. 11.]
 [ 8.  5. 13.]]
Round: 
 [[91. 31. 11.]
 [ 8.  5. 14.]]
Ceil: 
 [[91. 31. 12.]
 [ 9.  6. 14.]]


# **Indexing** **and** **Slicing**

In [2]:
oneD = np.arange(10)
twoD = np.arange(1,13).reshape(3,4)
threeD = np.arange(27).reshape(3,3,3)

In [ ]:
print(oneD)
print(oneD[-1])

[0 1 2 3 4 5 6 7 8 9]
9


In [ ]:
print(twoD)
print(twoD[1,2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
7


In [4]:
threeD

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [5]:
threeD[1,0,1]

np.int64(10)

In [ ]:
oneD

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#slicing
oneD[2:5]

array([2, 3, 4])

In [ ]:
twoD

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
twoD[:,2]

array([ 3,  7, 11])

In [ ]:
twoD[2,:]

array([ 9, 10, 11, 12])

In [ ]:
twoD[1:,1:3]

array([[ 6,  7],
       [10, 11]])

In [ ]:
twoD[::2,1:4:2]

array([[ 2,  4],
       [10, 12]])

In [6]:
threeD

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [9]:
threeD[1,:,1]

array([10, 13, 16])

In [11]:
threeD[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

# **Iteration**

In [12]:
oneD

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
for i in oneD:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [15]:
twoD

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [16]:
for i in twoD:
    print(i)

[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]


In [17]:
threeD

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [18]:
for i in threeD:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [19]:
for i in np.nditer(threeD):
    print(i)


0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
