<a href="https://colab.research.google.com/github/Ziyan-spec/Numpy-/blob/main/Numpy_Tricks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# **Sorting**

In [ ]:
#sort
a = np.random.randint(1,100,15)
print(a)
print(f"Sorted in Ascending order: {np.sort(a)}")
print(f"In descending order : {np.sort(a)[::-1]}")

[57 19 28 72 37 44 94  4 82 46 16  1 28 64 58]
Sorted in Ascending order: [ 1  4 16 19 28 28 37 44 46 57 58 64 72 82 94]
In descending order : [94 82 72 64 58 57 46 44 37 28 28 19 16  4  1]


In [ ]:
#2D array
b = np.random.randint(1,100,24).reshape(6,4)
print(b)

[[ 2 60 91 49]
 [17 84 93 39]
 [83 76  7  4]
 [10 88 50 24]
 [68 95  9 40]
 [45 97 15 47]]


In [ ]:
#sorting of 2D array
np.sort(b, axis=0)

array([[ 2, 60,  7,  4],
       [10, 76,  9, 24],
       [17, 84, 15, 39],
       [45, 88, 50, 40],
       [68, 95, 91, 47],
       [83, 97, 93, 49]])

# **Append**

In [ ]:
a

array([57, 19, 28, 72, 37, 44, 94,  4, 82, 46, 16,  1, 28, 64, 58])

In [ ]:
np.append(a,290)

array([ 57,  19,  28,  72,  37,  44,  94,   4,  82,  46,  16,   1,  28,
        64,  58, 290])

In [ ]:
b

array([[ 2, 60, 91, 49],
       [17, 84, 93, 39],
       [83, 76,  7,  4],
       [10, 88, 50, 24],
       [68, 95,  9, 40],
       [45, 97, 15, 47]])

In [ ]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[ 2., 60., 91., 49.,  1.],
       [17., 84., 93., 39.,  1.],
       [83., 76.,  7.,  4.,  1.],
       [10., 88., 50., 24.,  1.],
       [68., 95.,  9., 40.,  1.],
       [45., 97., 15., 47.,  1.]])

In [ ]:
b.shape

(6, 4)

In [ ]:
b.shape[0]     #give no. of rows

6

In [ ]:
b.shape[1]     #give no. of columns

4

# **Concatenate**

In [ ]:
a = np.arange(6,12).reshape(2,3)
a

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
b = np.arange(6).reshape(2,3)
b

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
np.concatenate((a,b), axis=1)

array([[ 6,  7,  8,  0,  1,  2],
       [ 9, 10, 11,  3,  4,  5]])

# **Unique**

In [ ]:
a = np.array([1,1,2,2,3,4,4,4,5,5,5,6,6])
a

array([1, 1, 2, 2, 3, 4, 4, 4, 5, 5, 5, 6, 6])

In [ ]:
np.unique(a)

array([1, 2, 3, 4, 5, 6])

# **Expand_dimension**

In [ ]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
e = np.expand_dims(a, axis=1)
print(e)
print(e.shape)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
(10, 1)


In [ ]:
e2 = np.expand_dims(a,axis=0)
print(e2)
e2.shape

[[0 1 2 3 4 5 6 7 8 9]]


(1, 10)

# **Where**, **argmax**, **argmin**

In [ ]:
#where
a = np.random.randint(1,100,10)
a

array([49, 67, 25, 15, 16, 48,  9, 41, 35, 75])

In [ ]:
#find all the indices greater than 50
np.where(a>50)

(array([1, 9]),)

In [ ]:
#find al the indices greater than 50 and replace elements with 0
np.where(a>50,0,a)   #np.where(condition,true,false)

array([49,  0, 25, 15, 16, 48,  9, 41, 35,  0])

In [ ]:
#argmax
np.argmax(a)    #give index of maximum element

np.int64(9)

In [ ]:
#argmin
np.argmin(a)

np.int64(6)

# **Cumulative** **Sum** **and** **Product**

In [ ]:
#cumilative sum
print(a)
print(np.cumsum(a))

[49 67 25 15 16 48  9 41 35 75]
[ 49 116 141 156 172 220 229 270 305 380]


In [ ]:
print(b)
print(np.cumsum(b,axis=1))

[[0 1 2]
 [3 4 5]]
[[ 0  1  3]
 [ 3  7 12]]


In [ ]:
#cumilative product
np.cumprod(a)

array([             49,            3283,           82075,         1231125,
              19698000,       945504000,      8509536000,    348890976000,
        12211184160000, 915838812000000])

# **Percentile** **and** **histogram**

In [ ]:
#percentile
print(a)
np.percentile(a,100)

[49 67 25 15 16 48  9 41 35 75]


np.float64(75.0)

In [ ]:
np.percentile(a,50)

np.float64(38.0)

In [ ]:
np.median(a)

np.float64(38.0)

In [ ]:
#Histogram --> give no. of elements in each bins
a

array([49, 67, 25, 15, 16, 48,  9, 41, 35, 75])

In [ ]:
np.histogram(a,bins=[0,20,40,60,80,100])

(array([3, 2, 3, 2, 0]), array([  0,  20,  40,  60,  80, 100]))

# **Correlation**

In [ ]:
salary = np.random.randint(5000,80000,10)
experience= np.arange(10)
print(salary)
print(experience)

[33512 44522 73639 53209 12747 54582 37423 78493 12507 20302]
[0 1 2 3 4 5 6 7 8 9]


In [ ]:
np.corrcoef(salary,experience)

array([[ 1.        , -0.25466851],
       [-0.25466851,  1.        ]])

# **isin**, **flip**, **get**, **delete**

In [ ]:
#isin
print(a)
np.isin(a,[10,80,25])

[60 67 25 15 16 48  9 41 35 75]


array([False, False,  True, False, False, False, False, False, False,
       False])

In [ ]:
a[np.isin(a,[10,80,25])]

array([25])

In [ ]:
#flip
np.flip(a)

array([75, 35, 41,  9, 48, 16, 15, 25, 67, 60])

In [ ]:
b

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
np.flip(b)

array([[5, 4, 3],
       [2, 1, 0]])

In [ ]:
np.flip(b,axis=0)

array([[3, 4, 5],
       [0, 1, 2]])

In [ ]:
#put
np.put(a,0,890)   #changes the existing array and added 890

In [ ]:
a

array([890,  67,  25,  15,  16,  48,   9,  41,  35,  75])

In [ ]:
#delete
print(a)
np.delete(a,1)

[890  67  25  15  16  48   9  41  35  75]


array([890,  25,  15,  16,  48,   9,  41,  35,  75])

# **Set** **functions** **and** **clip**

In [ ]:
m = np.array([1,2,3,4,5])
n = np.array([3,5,6,7])
print(f"m = {m}")
print(f"n = {n}")

m = [1 2 3 4 5]
n = [3 5 6 7]


In [ ]:
#union
np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
#intersection
np.intersect1d(m,n)

array([3, 5])

In [ ]:
#symetric diffrence
np.setdiff1d(m,n)

array([1, 2, 4])

In [ ]:
#symetric diffrence
np.setdiff1d(n,m)

array([6, 7])

In [ ]:
#xor --> it gives (m union n)-(m intersection n)
np.setxor1d(m,n)

array([1, 2, 4, 6, 7])

In [ ]:
#isin
np.isin(m,5)

array([False, False, False, False,  True])

In [ ]:
#clip
print(a)
np.clip(a,a_max=80,a_min=30)

[890  67  25  15  16  48   9  41  35  75]


array([80, 67, 30, 30, 30, 48, 30, 41, 35, 75])